version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/node"
        versions: [">=24.0.0"]
      - dependency-name: "eslint"
        versions: [">=9.0.0"]
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      types:
        patterns:
          - "@types/*"
      nextjs:
        patterns:
          - "eslint-config-next"
          - "next"
      emotion:
        patterns:
          - "@emotion/*"
